CREATE USER DEV4_FINAL IDENTIFIED BY DEV4_FINAL;
GRANT CONNECT, RESOURCE TO DEV4_FINAL;
GRANT ALTER SESSION TO DEV4_FINAL;
CONN DEV4_FINAL/DEV4_FINAL;

CREATE TABLE MEMBER(
	MEMBERSEQ NUMBER(8) NOT NULL, 
	MEMBERID VARCHAR2(16),
	PASSWORD VARCHAR2(16),
	NAME VARCHAR2(50) NOT NULL,
	NICKNAME VARCHAR2(16),
	ADDRESS1 VARCHAR2(100),
	ADDRESS2 VARCHAR2(100),
	PHONENUMBER VARCHAR2(11) NOT NULL,
	EMAIL VARCHAR2(40),
	BIRTHDAY VARCHAR2(10),
	SEX VARCHAR2(6),
	GRADE CHAR(1) DEFAULT 0 NOT NULL,
	ALARMSET VARCHAR2(255),
	FOLLOWSET VARCHAR2(255),
	FLATFORM CHAR(1) DEFAULT 'S' NOT NULL,
	CONSTRAINT MEMBER_PK PRIMARY KEY(MEMBERSEQ)
);

CREATE TABLE BAKERY(
	COPREGNUM NUMBER(10) NOT NULL,
	MANAGER VARCHAR2(50) NOT NULL,
	STORENAME VARCHAR2(50) NOT NULL,
	STOREADRESS1 VARCHAR2(100) NOT NULL,
	STOREADRESS2 VARCHAR2(100) NOT NULL,
	STORECONTACT VARCHAR2(11) NOT NULL,
	BAKERYPATH VARCHAR2(255) NOT NULL,
	BUSINESSHOUR VARCHAR2(20) NOT NULL,
	HOLIDAY VARCHAR2(100),
	SPECIALHOLIDAY VARCHAR2(100),
	EATABLE CHAR(1) NOT NULL,
	LATITUDE VARCHAR2(10) NOT NULL,
	LONGITUDE VARCHAR2(10) NOT NULL,
	BOARDSET CHAR(1) NOT NULL,
	MEMBERSEQ NUMBER(8) NOT NULL,
	CONSTRAINT BAKERY_FK FOREIGN KEY(MEMBERSEQ) REFERENCES MEMBER(MEMBERSEQ) ON DELETE CASCADE,
	CONSTRAINT BAKERY_PK PRIMARY KEY(MEMBERSEQ)
);	

CREATE TABLE FOOD(
	FOODSEQ NUMBER(8) NOT NULL,
	FOODNAME VARCHAR2(50) NOT NULL,
	KIND VARCHAR2(50) NOT NULL,
	FOODPATH VARCHAR2(255) NOT NULL,
	PRICE NUMBER(8) NOT NULL,	
	SALETIME VARCHAR2(8),
	BAKERYSEQ NUMBER(8) NOT NULL,
	CONSTRAINT FOOD_FK FOREIGN KEY(BAKERYSEQ) REFERENCES BAKERY(MEMBERSEQ) ON DELETE CASCADE,
	CONSTRAINT FOOD_PK PRIMARY KEY(FOODSEQ)
);	

CREATE TABLE ARTICLE(
	ARTICLESEQ NUMBER(8) NOT NULL,
	TITLE VARCHAR2(100) NOT NULL,
	WRITERSEQ NUMBER(8) NOT NULL,
	WRITERNICKNAME VARCHAR2(16) NOT NULL,
	REGDATE VARCHAR2(10) NOT NULL,
	SCORE NUMBER(1),
	REPORT VARCHAR2(255),
	BAKERYSEQ NUMBER(8) NOT NULL,
	CONSTRAINT ARTICLE_FK FOREIGN KEY(BAKERYSEQ) REFERENCES BAKERY(MEMBERSEQ) ON DELETE CASCADE,
	CONSTRAINT ARTICLE_PK PRIMARY KEY(ARTICLESEQ)	
);

CREATE TABLE CONTENT(
	ARTICLESEQ NUMBER(8) NOT NULL,
	REVIEW VARCHAR2(255) NOT NULL,
	ARTICLEPATH VARCHAR2(255),
	REPLY VARCHAR2(255),
	CONSTRAINT CONTENT_FK FOREIGN KEY(ARTICLESEQ) REFERENCES ARTICLE(ARTICLESEQ) ON DELETE CASCADE,
	CONSTRAINT CONTENT_PK PRIMARY KEY(ARTICLESEQ)	
);

COMMIT;
